### ISSUE TITLE
窗口异常

### ISSUE THREAD

**Issue by BlackTravel** [TheRamU/Fay#10]
python main.py  窗
![QQ截图20230318165113](https://user-images.githubusercontent.com/65138134/226095540-310b59cb-6356-45c8-aeac-c3ce8b4247bf.png)
![QQ截图20230318165051](https://user-images.githubusercontent.com/65138134/226095546-45e87c4d-3ba4-4d4b-9083-97853e600ab0.png)
口显示只有 icon 和 title ， 其他的一片空白 ，也没有报错 ，不知道问题出现在哪里

**Comment by xszyou** [comment]
通常是内存不足导致的html懒加载，可以再稍等片刻就出来了
