### ISSUE TITLE
fay控制器窗口是灰的

### ISSUE THREAD

**Issue by ahkimkoo** [TheRamU/Fay#3]
ubuntu22， python3.10， 启动以后没有报错，fay打开的窗口是灰色没有任何内容。
![Selection_011](https://user-images.githubusercontent.com/207163/208332112-939a54f8-17d7-446b-9ea9-2ccdec259262.png)

**Comment by xszyou** [comment]
可以试试重启一下电脑，ui是lazy load的，会在内存不足时延时加载
