### ISSUE TITLE
本地5000端口占用

### ISSUE THREAD

**Issue by dzgdp888** [TheRamU/Fay#49]
运行main.py之后提示地址占用，应该在哪修改默认端口

**Comment by dzgdp888** [comment]
<img width="567" alt="image" src="https://github.com/TheRamU/Fay/assets/13160185/edc4d5f8-4dc5-4830-a180-50caf1a50c33">

**Comment by withgogo** [comment]
精确搜索一下 5000， 然后替换成其他端口就好了

**Comment by dzgdp888** [comment]
嗯，我是这么改的，建议统一配置下，不要每个方法里都直接写。mac系统5000端口是airdrop的，关闭很不方便。
