### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by Imccccc** [TheRamU/Fay#5]
[17:50:34][系统] 开启核心服务...
[1]    78941 illegal hardware instruction  python main.py

**Comment by xszyou** [comment]
请联系我qq467665317，我会协助你找出原因

**Comment by thesky2017** [comment]
demo你跑通了吗

**Comment by Imccccc** [comment]
应该是硬件问题。后来被协助去了别的而项目。这个issue先关了吧。
