### ISSUE TITLE
python main.py: Qt Error

### ISSUE THREAD

**Issue by dijkstra-mose** [TheRamU/Fay#71]
Ubuntu 22.0.4
Anaconda3 Python 3.10

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/work/anaconda3/envs/fay/lib/python3.10/site-packages/cv2/qt/plugins" even though it was found.

pip list | grep Qt
PyQt5                          5.15.9

Qt用各种方法装了很多遍也没用。

**Comment by xiaogang-github** [comment]
老哥，你是怎么解决的啊，能分享一下思路吗
